version: "3.9"

services:
  api:
    image: fastapi-test
    container_name: fastapi-test
    ports:
      - "9000:8000"
    environment:
      MONGO_URI: mongodb://mongo:27017/sample_db
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:7
    container_name: fastapi-mongo
    ports:
      - "27018:27017"   # HOST access enabled
    volumes:
      - fastapi_mongo_data:/data/db
    restart: unless-stopped

volumes:
  fastapi_mongo_data:

